### ISSUE TITLE
Continue play in background 

### ISSUE THREAD

**Issue by PanderMusubi** [martykan/webTube#46]
Please continue playing in the background as a webbrowser also can.

**Comment by ildar** [comment]
FYI, vlc has an interesting feature: it can dynamically switch from video
to audio-only and back by pressing a button.

**Comment by PanderMusubi** [comment]
That could even be a setting to do that automatically when switching to background and foreground

**Comment by martykan** [comment]
I added an option to the menu to disable/enable background play, so everyone can be happy.

**Comment by PanderMusubi** [comment]
Thanks for adding it, however, the current version on F-Droid does not comply to when indicated that playing in background is allowed. Could please you reopen this issue and fix this?

**Comment by martykan** [comment]
@PanderMusubi Sorry, I didn't exactly understand. Background play still works in the latest version, by default. If you don't want background play, you can turn it off in the menu.

**Comment by PanderMusubi** [comment]
Ah, no it doesn't work on my device. A One Plus One with Cyanogen.

**Comment by martykan** [comment]
And it used to work?

**Comment by PanderMusubi** [comment]
no

**Comment by martykan** [comment]
Aha! I will look into it.

**Comment by breversa** [comment]
Same here : background playback does not work, though the notification bar displays the "headphone" icon and the notification drawer displays the video name and a pause button.

WebTube 1.1 (F-Droid) on Samsung Galaxy Nexus (maguro) running CyanogenMod 12.1/Android 5.1.1

**Comment by brunetton** [comment]
Same here :  "headphone" icon with video name and a pause button, but no sound. 
Webtube 1.1 (f-droid) / galaxy S5 / Android 6.0.1 stock

**Comment by Penguin-Guru** [comment]
"Play in background" box is checked but neither audio nor video play once app is placed in background. This has been the case since Android 6.0 but, since upgrading from 7.0 to 8.0, audio will no longer continue to play after I press the hardware button to sleep my phone. This is literally the only feature I need from a Youtube app, please let me know if you would like any additional information. My phone is a Pixel.

Unrelated, the feature to download videos links to a web page with several download sources. All of the sources I tried download a suspicious binary file... Am I missing something here?
